---

- name: Stop autofs service
  ansible.builtin.service:
    name: autofs
    state: stopped
  listen: redo mounts

- name: Unmount autofs mounts
  ansible.builtin.command: umount -a -t autofs
  listen: redo mounts

- name: Start autofs service
  ansible.builtin.service:
    name: autofs
    state: started
  listen: redo mounts

- name: Restart prometheus container
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: '{{ lookup("vars", sonarr_prefix + "_prometheus_basics_name") }}'
    state: started
    comparisons:
      '*': ignore
    restart: true
    stop_timeout: 10
  register: restart_sonarr_prometheus_docker
  retries: 5
  delay: 10
  until: restart_sonarr_prometheus_docker is succeeded
  listen: restart prometheus

- name: Restart recyclarr container
  community.docker.docker_container:
    container_default_behavior: compatibility
    name: '{{ lookup("vars", sonarr_prefix + "_recyclarr_basics_name") }}'
    state: started
    comparisons:
      '*': ignore
    restart: true
    stop_timeout: 10
  register: restart_sonarr_recyclarr_docker
  retries: 5
  delay: 10
  until: restart_sonarr_recyclarr_docker is succeeded
  listen: restart recyclarr