---

################################
# BASICS
################################

sonarr_prometheus_basics_name: 'prometheus'
sonarr_prometheus_basics_image_repo: 'prom/prometheus'
sonarr_prometheus_basics_image_tag: 'latest'
sonarr_prometheus_basics_restart_policy: 'unless-stopped'

################################
# NETWORK
################################

sonarr_prometheus_network: 'prometheus'
sonarr_prometheus_network_driver: []
sonarr_prometheus_network_subnet: []

################################
# ENV
################################

sonarr_prometheus_env_timezone: []
sonarr_prometheus_env_puid: []
sonarr_prometheus_env_pgid: []

################################
# PORTS
################################

sonarr_prometheus_ports_host: '9090'
sonarr_prometheus_ports_cont: '9090'

################################
# PATHS
################################

sonarr_prometheus_paths_folder: '{{ sonarr_prometheus_basics_name }}'  # name of prometheus config folder
sonarr_prometheus_paths_location: '/opt/{{ sonarr_prometheus_paths_folder }}'  # path of prometheus config folder
sonarr_prometheus_paths_data_location: '{{ sonarr_prometheus_paths_location }}/data'  # path where prometheus metrics are stored
                                                                                      # be mindful of metrics retention and size

################################
# BINDS
################################

sonarr_prometheus_binds_config_mapping:
  - '{{ sonarr_prometheus_paths_location }}/prometheus.yml:/etc/prometheus/prometheus.yml'

sonarr_prometheus_binds_data_mapping: 
  - '{{ sonarr_prometheus_paths_data_location }}:/data'

################################
# TRAEFIK
################################
  
sonarr_prometheus_traefik_subdomain: '{{ sonarr_prometheus_basics_name }}'
sonarr_prometheus_traefik_domain: []
sonarr_prometheus_traefik_network: 'traefik_proxy'
sonarr_prometheus_traefik_port: '9090'

################################
# CLOUDFLARE
################################

sonarr_prometheus_cloudflare_record_type: 'A'  ## A (IPV4), AAAA (IPV6), CNAME, etc
sonarr_prometheus_cloudflare_proxy: 'true'  ## true for cloudflare DNS SSL
sonarr_prometheus_cloudflare_api_token: []

################################
# METRICS
################################

sonarr_prometheus_metrics_retention_time: '15d'
sonarr_prometheus_metrics_retention_size: '0'  ## 0 for disabled. Use size units, i.e, 500MB, 2GB, 1TB, etc.

################################
# EXPORTER
################################

sonarr_prometheus_exporter_name: '{{ sonarr_basics_name }}_exporter'
sonarr_prometheus_exporter_image_repo: 'ghcr.io/onedr0p/exportarr'
sonarr_prometheus_exporter_image_tag: 'v2.0.1'
sonarr_prometheus_exporter_restart_policy: 'unless-stopped'
sonarr_prometheus_exporter_host_port: '9707' 
sonarr_prometheus_exporter_cont_port: '9707'

