---

################################
# sonarr
################################

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ sonarr_cloudflare_api_token }}'
    zone: '{{ sonarr_cloudflare_zone }}'
    state: absent
    type: CNAME
    record: '{{ sonarr_cloudflare_record }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ sonarr_cloudflare_api_token }}'
    zone: '{{ sonarr_cloudflare_zone }}'
    state: absent
    type: A
    record: '{{ sonarr_cloudflare_record }}'

- name: Get public ip for DNS tasks
  block:
    - name: Get public IP
      community.general.ipify_facts:
        timeout: 20
      delegate_to: localhost
      register: public_ip

    - name: Public IP output
      ansible.builtin.debug:
        msg: '{{ ipify_public_ip }}'

- name: Add sonarr DNS record
  community.general.cloudflare_dns:
    api_token: '{{ sonarr_cloudflare_api_token }}'
    zone: '{{ sonarr_cloudflare_zone }}'
    state: present
    solo: true
    proxied: '{{ sonarr_cloudflare_proxy }}'
    type: '{{ sonarr_cloudflare_record_type }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ sonarr_cloudflare_record }}'
  register: sonarr_cloudflare_record_creation_status

- name: Tasks on success
  when: sonarr_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        sonarr_cloudflare_record_print: '{{ (sonarr_cloudflare_record == sonarr_cloudflare_zone) | ternary(sonarr_cloudflare_zone, sonarr_cloudflare_record + "." + sonarr_cloudflare_zone) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ sonarr_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ sonarr_cloudflare_proxy }}'
