---

- name: Remove existing CNAME DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lookup("vars", sonarr_prefix + "_prometheus_cloudflare_api_token") }}'
    zone: '{{ lookup("vars", sonarr_prefix + "_prometheus_traefik_domain") }}'
    state: absent
    type: CNAME
    record: '{{ lookup("vars", sonarr_prefix + "_prometheus_traefik_subdomain") }}'

- name: Remove existing A DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lookup("vars", sonarr_prefix + "_prometheus_cloudflare_api_token") }}'
    zone: '{{ lookup("vars", sonarr_prefix + "_prometheus_traefik_domain") }}'
    state: absent
    type: A
    record: '{{ lookup("vars", sonarr_prefix + "_prometheus_traefik_subdomain") }}'

- name: Add DNS record
  community.general.cloudflare_dns:
    api_token: '{{ lookup("vars", sonarr_prefix + "_prometheus_cloudflare_api_token") }}'
    zone: '{{ lookup("vars", sonarr_prefix + "_prometheus_traefik_domain") }}'
    state: present
    solo: true
    proxied: '{{ lookup("vars", sonarr_prefix + "_prometheus_cloudflare_proxy") }}'
    type: '{{ lookup("vars", sonarr_prefix + "_prometheus_cloudflare_record_type") }}'
    value: '{{ ipify_public_ip }}'
    record: '{{ lookup("vars", sonarr_prefix + "_prometheus_traefik_subdomain") }}'
  register: sonarr_prometheus_cloudflare_record_creation_status

- name: Tasks on success
  when: sonarr_prometheus_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        sonarr_prometheus_cloudflare_record_print: '{{ (lookup("vars", sonarr_prefix + "_prometheus_traefik_subdomain") == lookup("vars", sonarr_prefix + "_prometheus_traefik_domain")) | ternary(lookup("vars", sonarr_prefix + "_prometheus_traefik_domain"), lookup("vars", sonarr_prefix + "_prometheus_traefik_subdomain") + "." + lookup("vars", sonarr_prefix + "_prometheus_traefik_domain")) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ sonarr_prometheus_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ lookup("vars", sonarr_prefix + "_prometheus_cloudflare_proxy") }}'
