---

- name: Add Prometheus DNS record
  when: sonarr_prometheus_cloudflare_is_enabled
  block:
    - name: Remove existing CNAME DNS record
      community.general.cloudflare_dns:
        api_token: '{{ sonarr_prometheus_cloudflare_api_token }}'
        zone: '{{ sonarr_prometheus_cloudflare_zone }}'
        state: absent
        type: CNAME
        record: '{{ sonarr_prometheus_cloudflare_record }}'

    - name: Remove existing A DNS record
      community.general.cloudflare_dns:
        api_token: '{{ sonarr_prometheus_cloudflare_api_token }}'
        zone: '{{ sonarr_prometheus_cloudflare_zone }}'
        state: absent
        type: A
        record: '{{ sonarr_prometheus_cloudflare_record }}'

    - name: Add sonarr DNS record
      community.general.cloudflare_dns:
        api_token: '{{ sonarr_prometheus_cloudflare_api_token }}'
        zone: '{{ sonarr_prometheus_cloudflare_zone }}'
        state: present
        solo: true
        proxied: '{{ sonarr_prometheus_cloudflare_proxy }}'
        type: '{{ sonarr_prometheus_cloudflare_record_type }}'
        value: '{{ ipify_public_ip }}'
        record: '{{ sonarr_prometheus_cloudflare_record }}'
      register: sonarr_prometheus_cloudflare_record_creation_status

- name: Tasks on authelia DNS record success
  when:
    - sonarr_prometheus_cloudflare_is_enabled
    - sonarr_prometheus_cloudflare_record_creation_status is succeeded
  block:
    - name: Set 'dns_record_print' variable
      ansible.builtin.set_fact:
        sonarr_prometheus_cloudflare_record_print: '{{ (sonarr_prometheus_cloudflare_record == sonarr_prometheus_cloudflare_zone) | ternary(sonarr_prometheus_cloudflare_zone, sonarr_prometheus_cloudflare_record + "." + sonarr_prometheus_cloudflare_zone) }}'

    - name: Display DNS record creation status
      ansible.builtin.debug:
        msg: 'DNS A Record for "{{ sonarr_prometheus_cloudflare_record_print }}" set to "{{ ipify_public_ip }}" was added. Proxy: {{ sonarr_prometheus_cloudflare_proxy }}'